name: dupli
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  firedart: ^0.9.8
  http: ^0.13.3
  firebase_core: ^2.30.0
  firebase_auth: ^4.3.0
  shelf: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
